### ISSUE TITLE
Simpler inverse for view matrix

### ISSUE THREAD

**Issue by xrmonitors** [microsoft/OpenXR-SDK-VisualStudio#11]
https://github.com/microsoft/OpenXR-SDK-VisualStudio/blob/9336599e922eaf03f4fad928ba122275a3b677d9/samples/BasicXrApp/CubeGraphics.cpp#L382

This should probably be LoadInvertedXrPose() so it's not inverting a matrix

**Comment by yl-msft** [comment]
Good suggestion.  Fixed in recent changes.
