### ISSUE TITLE
Win32 sample app crashes on GTX 960 M as of commit #25

### ISSUE THREAD

**Issue by syntheticmagus** [microsoft/OpenXR-SDK-VisualStudio#24]
The full error that seems to be the cause of the crash is pasted below. I believe it has to do with the absence of a GPU feature (presumably VPRT) which is required as of commit #20. I also experience issues with the UWP app, but I have not yet confirmed that it's the same issue. Commit #19 functions on my machine and unblocks me for now.

```
D3D11 ERROR: ID3D11Device::CreateVertexShader: Shader uses ability to feed viewport and/or array index from any shader feeding the rasterizer, but the device does not support this. To check for support, check device caps via the CheckFeatureSupport() API [ STATE_CREATION ERROR #166: CREATEVERTEXSHADER_INVALIDSHADERBYTECODE]
Exception thrown at 0x00007FFB28F2A839 in BasicXrApp_win32.exe: Microsoft C++ exception: _com_error at memory location 0x00000046DBBDDED0.
Exception thrown at 0x00007FFB28F2A839 in BasicXrApp_win32.exe: Microsoft C++ exception: std::logic_error at memory location 0x00000046DBBDDD38.
```

**Comment by yl-msft** [comment]
This sample now demos the best practice for OpenXR running on Hololens and therefore used VPRT.   If you need to run this sample in older GPU you have to stay before the #19, or upgrade your GPU ;).  

We will consider to fork more samples in different tech    At this moment we’d like to keep the default recommendation to be the best on Hololens 2.   Thanks.

**Comment by syntheticmagus** [comment]
Makes sense. Thanks for letting me know!
