### ISSUE TITLE
BasicXrApp_uwp Error

### ISSUE THREAD

**Issue by prodev2015** [microsoft/OpenXR-SDK-VisualStudio#28]
I am just trying to run BasicXrApp and the app doesn't start and an error occurs.
The error says "Unable to activate Windows Store app. The activation request failed with error 'The app didn't start'"
What happened and how should I do?

**Comment by brycehutchings** [comment]
Are you trying to run it locally or remotely (like on a HoloLens emulator)? If you run with a debugger (F5), do you see any unhandled exception or does the activation error still happen? If running locally, have you enabled developer mode in the Settings app? Are you using VS2019?

**Comment by yl-msft** [comment]
Since there's no new information, i will close this issue as not repro.  @prodev2015 Please let us know more details if this still happens to you.  Thanks
