### ISSUE TITLE
Sample no longer works on older dx11 cards as it requires VPAndRTArrayIndexFromAnyShaderFeedingRasterizer

### ISSUE THREAD

**Issue by Sanakan8472** [microsoft/OpenXR-SDK-VisualStudio#31]
The check for VPAndRTArrayIndexFromAnyShaderFeedingRasterizer is after the CompileShader call which already fails so it is never executed. Even if it was, the message "This sample requires VPRT support. Adjust sample shaders on GPU without VRPT." isn't very helpful as adjust means just rewrite the entire thing to use a geometry shader.
For accesibility, as a basic sample the bar for entry shouldn't be this high. It's supposed to demo OpenXR, it doesn't need to be the world's fastest cube renderer. I would propose a switch to support older cards instead of outright failing.

**Comment by yl-msft** [comment]
@Sanakan8472   Thanks for your feedback.  The current BasicXrApp sample is focused on [the best practice to use OpenXR on Hololens 2](https://microsoft.visualstudio.com/DefaultCollection/Analog/_git/mixedreality.winxr/pullrequest/4104203)

You've got a fair point about the "basic" part of this basic sample.  Khronos GitHub repo has a "HelloXR" app designed for such simple usage.  Strongly recommend you to look there.
https://github.com/KhronosGroup/OpenXR-SDK-Source/tree/master/src/tests/hello_xr

**Comment by Sanakan8472** [comment]
Thanks for the tip, I'll try the Khronos sample instead. Your reasoning makes sense so feel free to close the ticket unless you think it would still be worthwhile to at least move the extension check before the compile call for the next person that runs into this.
