### ISSUE TITLE
Why when run BasicXrApp on HoloLens 2 Emulator, It's black sreen?

### ISSUE THREAD

**Issue by sinojelly** [microsoft/OpenXR-SDK-VisualStudio#4]
I compile BasicXrApp on Visual Studio 2017 with Debug/x64, package it to BasicXrApp_uwp_1.0.0.0_x64_Debug.appx,  then install it to HoloLens 2 Emulator through  Device Portal, and start it. It seems to be launched successful, I can hear the sound, and see the animation, but after that, there is only a black screen on the HoloLens 2 Emulator.

I don't know how to make the HoloLens 2 emulator to show the BasicXrApp.
Any help would be appreciated!
![start-basicxrapp-blackscreen](https://user-images.githubusercontent.com/520711/59155882-93d5db80-8ac4-11e9-9346-018d54985e96.PNG)

**Comment by yl-msft** [comment]
The default cubes placed in the world is probably behind your eye at this moment.  You might want to control your emulator to move back a bit so you can see the cubes in front of you.

**Comment by yl-msft** [comment]
The initial placement of the cube should be 1 meter in front of user.  But there was a bug in the code that cube was spawned at user's head.

#7 is fixing this issue.

**Comment by yl-msft** [comment]
Resolved in #7
