### ISSUE TITLE
two header files missing

### ISSUE THREAD

**Issue by MignonBelongie** [microsoft/OpenXR-SDK-VisualStudio#5]
I had to add two header files to get BasicXrApp_win32 to compile:

In samples/BasicXrApp/CubeGraphics.cpp:
`#include <list>`

In samples/BasicXrApp/OpenXrProgram.cpp:
`#include <unordered_map>`

**Comment by yl-msft** [comment]
Addressing this issue in #7

**Comment by yl-msft** [comment]
Resolved in #7
